# Generated by Django 3.0.3 on 2020-02-16 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodtaskerapp', '0002_auto_20200216_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='logo',
            field=models.ImageField(default='', upload_to='restaurant_logo/'),
        ),
    ]
