# Generated by Django 3.0.3 on 2020-02-16 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodtaskerapp', '0003_auto_20200216_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='logo',
            field=models.ImageField(upload_to='restaurant_logo/'),
        ),
    ]
